/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.mpmgc.robotswarm.app;
import javafx.application.Application;

public class App {
    public static void main(String[] args) {
        Application.launch(RobotSwarmApp.class,args);
    }
}
